Repository wrappid/auth-module, pull requests merged in 2024-07, with the labels that each got.

#89 UI and Verify otp fix
  app/components/layout/AuthLayout.js
  service/functions/auth.functions.ts
Labels: api, frontend, bugfix

#91 fix(global): :bug: otp missmatch fix
  app/components/LoginWithPassword.js
  app/components/RegisterOrResetPassword.js
  service/functions/auth.functions.ts
Labels: bug

#93 feat(utils): :zap: call ProfileBasic after successful login
  app/apis.registry.js
  app/components/LoginWithOtp.js
  app/components/LoginWithPassword.js
  app/components/RegisterOrResetPassword.js
  app/components/layout/AuthLayout.js
Labels: enhancement
