Repository wrappid/auth-module, pull requests merged in 2024-10, with the labels that each got.

#99 feat(global): :sparkles: social login hook function added
  service/functions/auth.functions.ts
  service/functions/soicial.login.function.ts
Labels: enhancement

#104 feat(global): :sparkles: social login code structure fix
  service/constants/constants.ts
  service/controllers.registry.ts
  service/controllers/social.auth.controller.ts
  service/functions/auth.functions.ts
  service/functions/soicial.login.function.ts
  service/routes.registry.ts
Labels: enhancement

#114 fix(core): :bug: fix after checkuserexist redirect wrong url
  app/components/CheckUserExist.js
  app/reducers/authReducer.js
Labels: bugfix

#119 style(core): :lipstick: social login message text give theme driven c…
  app/components/CheckUserExist.js
Labels: frontend

#124 bugfix: checkUserExist mobile fix
  app/components/CheckUserExist.js
  app/validations.registry.js
Labels: bugfix

#127 fix(config): :heavy_plus_sign: added bcrypt
  package-lock.json
  package.json
  service/test/checkLoginOrRegister.test.ts
  service/test/login.test.ts
Labels: bugfix

#128 feat(global): :lipstick: update ui of check user exist page
  app/components/CheckUserExist.js
  app/components/layout/AuthCustomFooter.js
  app/components/layout/AuthLayout.js
  app/styles/DefaultModuleStyles.js
Labels: enhancement
