Repository wrappid/auth-module, pull requests merged in 2024-03, with the labels that each got.

#49 fix: fixed the import
  app/components.registry.js
  app/components/AuthCustomFooter.js
  app/components/CheckUserExist.js
  app/components/LoginWithOtp.js
  app/components/LoginWithPassword.js
  app/components/ModuleComponent.js
  app/components/RegisterOrResetPassword.js
  app/components/layout/AuthLayout.js
  app/components/oldAuthContainer.js
  app/routes.registry.js
Labels: bugfix

#51 fix(global): :bug: fix refreshtoken
  package-lock.json
  package.json
  service/functions/auth.functions.ts
Labels: bug

#52 merge: development into main
  package-lock.json
  package.json
  service/functions/auth.functions.ts
Labels: enhancement

#54 enhancement: update template
  .eslintrc.js
  .github/workflows/create-tag.yml
  .wrappid/wrappid.meta.json
  ATTRIBUTIONS.md
  app/test/app.test.ts
  jest.config.js
  package-lock.json
  package.json
  scripts/attributions.gen.js
  service/controllers.registry.ts
  service/functions.registry.ts
  service/middlewares.registry.ts
  service/models.registry.ts
  service/routes.registry.ts
  service/tasks.registry.ts
  service/test/service.test.ts
  service/validations.registry.ts
Labels: enhancement

#55 merge: Development into main
  .eslintrc.js
  .github/workflows/create-tag.yml
  .wrappid/wrappid.meta.json
  ATTRIBUTIONS.md
  CHANGELOG.md
  app/test/app.test.ts
  jest.config.js
  package-lock.json
  package.json
  scripts/attributions.gen.js
  service/controllers.registry.ts
  service/functions.registry.ts
  service/middlewares.registry.ts
  service/models.registry.ts
  service/routes.registry.ts
  service/tasks.registry.ts
  service/test/service.test.ts
  service/validations.registry.ts
Labels: enhancement

#56 enhancement: auth layout related fix
  app/components/AuthCustomFooter.js
  app/components/CheckUserExist.js
  app/components/LoginWithOtp.js
  app/components/LoginWithPassword.js
  app/components/RegisterOrResetPassword.js
  app/components/layout/AuthContainer.js
  app/components/layout/AuthCustomFooter.js
  app/components/layout/AuthLayout.js
  app/styles/DefaultModuleStyles.js
  app/theme/authTheme.js
Labels: enhancement
