Repository wrappid/auth-module, pull requests merged in 2024-11, with the labels that each got.

#130 enhancement: auth restructure impact handled
  app/components.registry.js
  app/components/LoginWithOtp.js
  app/components/LoginWithPassword.js
  app/components/Register.js
  app/components/ResetPassword.js
  app/constants/app.constants.js
  app/functions.registry.js
  app/functions/sanity.functions.js
  app/reducers/authReducer.js
  app/types/authTypes.js
  app/validations.registry.js
  service/constants/constants.ts
  service/controllers.registry.ts
  service/controllers/auth.controller.ts
  service/functions.registry.ts
  service/functions/auth.functions.ts
  service/functions/auth.helper.functions.ts
  service/functions/soicial.login.function.ts
  service/functions/user.function.ts
  service/routes.registry.ts
  service/types/auth.types.ts
  service/validations/auth.validation.ts
Labels: api

#140 fix(global): :bug: changes in auth module so it can work in mobile app
  app/components/layout/AuthCustomFooter.js
  app/components/layout/AuthLayout.js
  app/styles/DefaultModuleStyles.js
Labels: bugfix

#144 fix(global): :bug: handle impact of style package
  app/components/LoginWithPassword.js
  app/components/layout/AuthLayout.js
  app/styles/DefaultModuleStyles.js
Labels: enhancement
